version: '3.7'
services:

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: on-failure

  app:
    build: ./management_system
    container_name: app
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: on-failure