version: '3.7'
services:

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: on-failure

  web:
    build: ./management_system
    container_name: web
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: on-failure

  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: "redis"
    depends_on:
      - db
    restart: on-failure

  celery:
    build: ./management_system
    container_name: celery
    entrypoint: celery -A core worker -l INFO -f celery_log.txt
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    restart: on-failure
