# Generated by Django 3.1.5 on 2021-01-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210112_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='position',
            name='project',
        ),
        migrations.AddField(
            model_name='position',
            name='opportunity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.opportunity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='opportunity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.opportunity', verbose_name='related opportunity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='utilization_current',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='project_start_date',
            field=models.DateField(),
        ),
    ]
