# Generated by Django 3.1.5 on 2021-01-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210112_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.opportunity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='opportunity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.opportunity', verbose_name='related opportunity'),
        ),
    ]
